// ---------------------------------------------------------------------------
// England structural dataset: Premier League (tier 1) + Championship (tier 2).
// Club/league names and stadiums are factual structural data; squads are
// generated by the fallback generator (§9). No protected player data ships.
// Reputations anchor squad strength and finances and are easily editable.
// ---------------------------------------------------------------------------

import type { Dataset, DatasetClub } from '../types/dataset';

const c = (
  name: string,
  shortName: string,
  abbrev: string,
  reputation: number,
  stadiumName: string,
  stadiumCapacity: number,
  primaryColor: string,
  secondaryColor = '#ffffff',
): DatasetClub => ({
  name,
  shortName,
  abbrev,
  reputation,
  stadiumName,
  stadiumCapacity,
  primaryColor,
  secondaryColor,
});

const premierLeague: DatasetClub[] = [
  c('Arsenal', 'Arsenal', 'ARS', 88, 'Emirates Stadium', 60704, '#EF0107'),
  c('Aston Villa', 'Villa', 'AVL', 78, 'Villa Park', 42657, '#95BFE5', '#670E36'),
  c('Bournemouth', 'Bournemouth', 'BOU', 66, 'Vitality Stadium', 11307, '#DA291C'),
  c('Brentford', 'Brentford', 'BRE', 67, 'Gtech Community Stadium', 17250, '#E30613'),
  c('Brighton', 'Brighton', 'BHA', 72, 'Amex Stadium', 31800, '#0057B8'),
  c('Chelsea', 'Chelsea', 'CHE', 85, 'Stamford Bridge', 40341, '#034694'),
  c('Crystal Palace', 'Palace', 'CRY', 69, 'Selhurst Park', 25486, '#1B458F', '#C4122E'),
  c('Everton', 'Everton', 'EVE', 71, 'Goodison Park', 39414, '#003399'),
  c('Fulham', 'Fulham', 'FUL', 68, 'Craven Cottage', 24500, '#000000'),
  c('Ipswich Town', 'Ipswich', 'IPS', 60, 'Portman Road', 30311, '#3A64A3'),
  c('Leicester City', 'Leicester', 'LEI', 70, 'King Power Stadium', 32261, '#003090'),
  c('Liverpool', 'Liverpool', 'LIV', 90, 'Anfield', 61276, '#C8102E'),
  c('Manchester City', 'Man City', 'MCI', 92, 'Etihad Stadium', 53400, '#6CABDD'),
  c('Manchester United', 'Man Utd', 'MUN', 87, 'Old Trafford', 74310, '#DA291C'),
  c('Newcastle United', 'Newcastle', 'NEW', 80, "St James' Park", 52305, '#241F20'),
  c('Nottingham Forest', 'Forest', 'NFO', 66, 'The City Ground', 30404, '#DD0000'),
  c('Southampton', 'Southampton', 'SOU', 63, "St Mary's Stadium", 32384, '#D71920'),
  c('Tottenham Hotspur', 'Spurs', 'TOT', 82, 'Tottenham Hotspur Stadium', 62850, '#132257'),
  c('West Ham United', 'West Ham', 'WHU', 74, 'London Stadium', 62500, '#7A263A', '#1BB1E7'),
  c('Wolverhampton', 'Wolves', 'WOL', 68, 'Molineux Stadium', 31750, '#FDB913', '#231F20'),
];

const championship: DatasetClub[] = [
  c('Blackburn Rovers', 'Blackburn', 'BLB', 55, 'Ewood Park', 31367, '#009EE0'),
  c('Bristol City', 'Bristol City', 'BRC', 52, 'Ashton Gate', 27000, '#E21C38'),
  c('Burnley', 'Burnley', 'BUR', 62, 'Turf Moor', 21944, '#6C1D45', '#99D6EA'),
  c('Cardiff City', 'Cardiff', 'CAR', 50, 'Cardiff City Stadium', 33280, '#0070B5'),
  c('Coventry City', 'Coventry', 'COV', 53, 'Coventry Building Society Arena', 32609, '#69B6E2'),
  c('Derby County', 'Derby', 'DER', 51, 'Pride Park', 33597, '#000000'),
  c('Hull City', 'Hull', 'HUL', 50, 'MKM Stadium', 25586, '#F18A00', '#000000'),
  c('Leeds United', 'Leeds', 'LEE', 64, 'Elland Road', 37792, '#FFFFFF', '#1D428A'),
  c('Luton Town', 'Luton', 'LUT', 54, 'Kenilworth Road', 11500, '#F78F1E'),
  c('Middlesbrough', 'Boro', 'MID', 57, 'Riverside Stadium', 34742, '#E21C38'),
  c('Millwall', 'Millwall', 'MIL', 48, 'The Den', 20146, '#001D5E'),
  c('Norwich City', 'Norwich', 'NOR', 58, 'Carrow Road', 27359, '#00A14E', '#FFF200'),
  c('Oxford United', 'Oxford', 'OXF', 44, 'Kassam Stadium', 12500, '#FFD200'),
  c('Plymouth Argyle', 'Plymouth', 'PLY', 45, 'Home Park', 17900, '#004A2F'),
  c('Portsmouth', 'Portsmouth', 'POR', 49, 'Fratton Park', 20899, '#001489'),
  c('Preston North End', 'Preston', 'PNE', 50, 'Deepdale', 23404, '#FFFFFF', '#B2B5B8'),
  c('Queens Park Rangers', 'QPR', 'QPR', 49, 'Loftus Road', 18439, '#1D5BA4'),
  c('Sheffield United', 'Sheff Utd', 'SHU', 60, 'Bramall Lane', 32050, '#EE2737'),
  c('Sheffield Wednesday', 'Sheff Wed', 'SHW', 51, 'Hillsborough', 39732, '#0066B3'),
  c('Stoke City', 'Stoke', 'STK', 53, 'bet365 Stadium', 30089, '#E03A3E'),
  c('Sunderland', 'Sunderland', 'SUN', 59, 'Stadium of Light', 49000, '#EB172B'),
  c('Swansea City', 'Swansea', 'SWA', 52, 'Swansea.com Stadium', 21088, '#FFFFFF', '#000000'),
  c('Watford', 'Watford', 'WAT', 56, 'Vicarage Road', 22200, '#FBEE23', '#ED2127'),
  c('West Bromwich Albion', 'West Brom', 'WBA', 57, 'The Hawthorns', 26688, '#122F67'),
];

const standardTiebreakers = ['points', 'goalDifference', 'goalsFor', 'headToHead'] as const;

export const ENGLAND_DATASET: Dataset = {
  schemaVersion: 1,
  name: 'England (Premier League + Championship)',
  description:
    'Structural England dataset for the MVP. Club/stadium facts only; player ' +
    'attributes are generated. Swap in a licensed dataset to play with real ' +
    'player data.',
  countries: [
    {
      id: 'GB',
      name: 'England',
      confederation: 'UEFA',
      leagues: [
        {
          name: 'Premier League',
          tier: 1,
          format: 'round_robin',
          numClubs: 20,
          rounds: 2,
          tiebreakers: [...standardTiebreakers],
          promotion: {
            autoPromote: 0,
            autoRelegate: 3,
            promotionPlayoffSlots: 0,
            relegationPlayoffSlots: 0,
          },
          conferences: null,
          clubs: premierLeague,
        },
        {
          name: 'Championship',
          tier: 2,
          format: 'round_robin',
          numClubs: 24,
          rounds: 2,
          tiebreakers: [...standardTiebreakers],
          promotion: {
            autoPromote: 2,
            autoRelegate: 3,
            promotionPlayoffSlots: 4, // 3rd–6th contest 1 promotion place
            relegationPlayoffSlots: 0,
          },
          conferences: null,
          clubs: championship,
        },
      ],
    },
  ],
};
